name: build

on:
  pull_request:
  push:
    branch:
      - master

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
            #- macos-latest
        ocaml-compiler:
          - 4.08.x
          - 4.13.x

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      # needed for depext to work
      - run: sudo apt-get update
        if: ${{ matrix.os == 'ubuntu-latest' }}

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          opam-depext-flags: --with-test

      - run: opam install . --deps-only --with-test

      - run: opam exec -- dune build @install -p opentelemetry,opentelemetry-lwt,opentelemetry-client-ocurl,opentelemetry-cohttp-lwt

      - run: opam exec -- dune build @lint

      # check that nothing changed
      - run: git diff --quiet --exit-code

      - run: opam exec -- dune build @runtest
        if: ${{ matrix.os == 'ubuntu-latest' }}
